### ISSUE TITLE
Can this version work with Curves?

### ISSUE THREAD

**Issue by adamearle** [aldrinsartfactory/stopmagic#11]
how hard  would it be to get this working with curves as well?

**Comment by aldrinmathew** [comment]
@adamearle 
I apologise for the late reply as I have too much going on right now. Making the addon work for curves depends on the way blender handles curve data and if that can be keyframed natively within blender. Because mesh data can be.
I do remember some parts of the old version of code that were related to curves.
There will have to be minor refactors to completely implement this. But I believe it is not going to be too much of a task to accomplish.

Please keep this issue open. I will provide updates as available.

**Comment by adamearle** [comment]
Curve data can be keyframed. I usually do it using the **AnimAll Addon**. Is this something that you think you are capable of doing? And if so how long do you think it will take you to it?
