### ISSUE TITLE
Some frames cannot be keyed

### ISSUE THREAD

**Issue by josephsdaniels** [aldrinsartfactory/stopmagic#2]
Some frames cannot be keyed. This has happened to me a number of times, but in the file I've attached, try creating a key pose at frame 18 with the Keyframe Mesh button. No key is created.  I'm using the addon in the latest official release of Blender 3.0, btw.

[HeartBubbles_v01.zip](https://github.com/aldrinsartfactory/stopmagic/files/8054815/HeartBubbles_v01.zip)

**Comment by aldrinmathew** [comment]
This has been fixed

#### Here is the explanation:

- This behaviour was caused by the addon checking for a preexisting
  mesh in the current frame, using the name of the meshes.
- The name system won't work as it will not be associated with the
  correct keyframe if the user moves the keyframe from the original
  position
- This has been fixed by checking the actual keyframes, for existing
  keyed meshes in the current frame

**Comment by aldrinmathew** [comment]
Thanks for the detailed description and the file.
